apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    method: fromcode
  name: nginx-stable
  namespace: kcl0026
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: nginxinc/nginx-unprivileged:stable
    name: nginx-stable
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
