import = ["~/.config/alacritty/themes/nord.toml"]

[font]
size = 12

[env]
TERM = "xterm-256color"

[font.normal]
family = "SpaceMono Nerd Font"

[window]
startup_mode = "Windowed"
decorations = "Full"

[window.padding]
x = 7
y = 0

[selection]
save_to_clipboard = true
